# Generated by Django 5.1.2 on 2025-08-30 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_order_orderitem_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False, help_text='If True, this product qualifies the order for free delivery.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='Mark as True if this product is a package/bundle.'),
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_component_in', to='myApp.product')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_links', to='myApp.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent', 'component'), name='uniq_bundle_component')],
            },
        ),
    ]
