# Generated by Django 5.1.2 on 2025-09-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_order_cancel_reason_orderitem_cancel_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog_covers/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author_name', models.CharField(default='SHARP Editorial', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('paragraph', 'Paragraph'), ('heading', 'Heading'), ('image', 'Image'), ('gallery2', '2-Image Row'), ('callout', 'Callout'), ('quote', 'Pull Quote'), ('product', 'Product Card')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=10)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('prod_query', models.CharField(blank=True, max_length=120)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='myApp.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
