# Generated by Django 5.1.2 on 2025-09-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_post_postblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='postblock',
            name='image1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='postblock',
            name='image2_url',
            field=models.URLField(blank=True),
        ),
    ]
