# Generated by Django 5.1.2 on 2025-09-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='myApp_order_product_023dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='postblock',
            index=models.Index(fields=['post', 'order'], name='myApp_postb_post_id_60e401_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_bundle'], name='myApp_produ_is_acti_edf8c9_idx'),
        ),
    ]
