# Generated by Django 5.1.2 on 2025-09-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='myApp_order_product_023dd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='postblock',
            name='myApp_postb_post_id_60e401_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='myApp_produ_is_acti_edf8c9_idx',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='confirm_token',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source',
            field=models.CharField(blank=True, help_text='e.g. footer_form, checkout, popup', max_length=64),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='ua',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
