# Generated by Django 5.1.2 on 2025-09-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Created (awaiting courier)'), ('60', 'Assign driver to pick up'), ('100', 'Picked up by driver'), ('120', 'Stored in warehouse'), ('130', 'Out for delivery'), ('170', 'Delivered to customer'), ('180', 'Returned from customer'), ('190', 'Item returned to returned shelf'), ('210', 'Returned to shipper (RTO)'), ('121', 'Departed to airport'), ('123', 'Departed from origin – Outgoing'), ('51', 'Departed from origin – Incoming'), ('56', 'Arrival to gateway – Incoming'), ('57', 'Under clearance – Incoming'), ('58', 'Customs released – Incoming')], default='0', max_length=20),
        ),
    ]
