# Generated by Django 5.1.2 on 2025-10-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity. For bundles, this tracks the bundle quantity separately from components.'),
        ),
    ]
