# Generated by Django 5.1.2 on 2025-11-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_order_promo_code_promo_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
