# Generated by Django 5.1.2 on 2025-11-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_about_contact_faq_footer_hero_navigation_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_sitewide',
            field=models.BooleanField(default=False, help_text='If checked, this promo applies automatically to all orders (no code needed). Only one sitewide promo can be active at a time.'),
        ),
    ]
